cksac/fake-rs

- src/faker/phone_number.rs
Avoids unused allocations
This might be a breaking change, but i think it should strictly allows more input types now.
> Use ´AsRef<str>` instead of `Into<String>`

- src/lib.rs
It reads a bit nicer IMHO. E.g.: `fake!(Name.name in zh_tw)` instead of `fake!(zh_tw; Name.name)` with a weird semicolon in there somewhere. It's totally subjective though – feel free to not do this 😄
> Add Macro Variant with "in <lang>"

- src/helper.rs
Maybe it's also a good idea to Re-export `rand`, if somebody wants to use `thread_rng`
> take_one - generic over `T: ?Sized`

- fake/src/impls/std/primitives.rs
Emscripten doesn't have 128-bit support.
> Allow crate to work on emscripten

- fake/Cargo.toml
- fake/examples/basic.rs
- fake/src/impls/std/collections/vec.rs
- fake/src/impls/std/path.rs
- fake/src/impls/std/result.rs
- fake/src/impls/std/string.rs
- fake/src/lib.rs
I just realized that there are crate examples, not quite discoverable.
Usually I need to do stuff offline so I think having offline documentation is good, since it is not easy to browse the README or the examples as compared to each specific items generated by rustdoc, having some explanation for the traits can roughly describes how the trait works.
Fix #46
> Add some top level docs

- fake/Cargo.toml
- fake/src/locales/mod.rs
- fake/tests/determinism.rs
I started by writing a small-ish proptest for determinism and extended it until it covered most faker implementations, macro-fying things as I went.
I found indeterminism in the ISBN fakers that stemmed from the use of a HashMap's `keys()` which have an indeterministic order. I simply replaced this with a `BTreeMap`, which always iterates in sorted order.
> test against & fix indeterminism

- fake/Cargo.toml
This removes an unneccessary dependency on time 0.1
> Don't require chrono's default features

- fake/Cargo.toml
- fake/src/faker/impls/mod.rs
- fake/src/faker/impls/time.rs
- fake/src/faker/mod.rs
- fake/src/impls/mod.rs
- fake/src/impls/time/mod.rs
- fake/src/locales/mod.rs
- fake/tests/determinism.proptest-regressions
- fake/tests/determinism.rs
Hey, thank you for the awesome library!
as you probably know, chrono is abandonned, and while the best alternative is still not completely decided, time looks like a good candidate.
This PR adds the `time` feature. It's mostly copy paste at this point, and there are a couple of unwraps lying around.
Happy to change anything you don't like.
I'm thinking of adding decimal support as well at some point.
> time: add chrono alternative with time lib

- fake/src/impls/decimal/mod.rs
- fake/tests/determinism.rs
As per request of @mothsART  in my [previous PR](https://github.com/cksac/fake-rs/pull/80), here are determinsm tests added to the Decimal fake types.
> [Scout] Add determinism to decimal

- README.md
Fixed a typo in the README.md file where a subheading was named `BareCode`. Changed the typo to Barcode.
> Typo BareCode -> Barcode

- fake/examples/fakers.rs
- fake/src/faker/impls/barcode.rs
- fake/src/faker/impls/mod.rs
- fake/src/faker/mod.rs
- fake/tests/determinism.rs
Fixed a typo within the source code where barecode was used instead of `barcode`.
The fix affects the module's name so it will break all current users that implement the `barecode` code.
I did a quick search on github for `barecode language:Rust` and `use crate::fake::barcode::raw::*;` on Google and neither turn up any projects using the function that was changed.
Might be best to fix this typo now rather than later when other projects might break.
> Fixed typo barecode -> barcode

- README.md
- fake/Cargo.toml
- fake/examples/fakers.rs
- fake/src/impls/bigdecimal/mod.rs
- fake/src/impls/mod.rs
- fake/src/lib.rs
- fake/tests/determinism.rs
Even if I want to use `rust_decimal` module, my current project use `bigdecimal-rs` as dependency. So I added the `bigdecimal` impls to the lib (which shamelessly use current `rust_decimal` module 😭).
> Add support for `bigdecimal-rs`

- dummy_derive/src/lib.rs
- fake/examples/derive.rs
- fake/tests/derive_macros.rs
@cksac Thanks for merging my other PRs.
As I was using the 'dummy" enhancement PR locally I found a few other niceties and expanded the test.
- this adds a "default" field option as well that will use Default:::default()
```rust
#[derive(Dummy)]
struct Obj(
#[dummy(default)]
String,
);
```
<del>
Then the second commit (please let me know if it is ok, or should be named different) adds a derive-level option of default_impl that will generate an impl of the Default trait that will simply call Faker.faker() (helpful for my test only structs)
```rust
#[derive(Dummy)]
#[dummy(default_impl)]
struct Obj {
pub value: i32,
}
let a : Obj = Default::default();
```
</del>
> Feat better dummy

- fake/Cargo.toml
- fake/examples/derive.rs
- fake/src/impls/mod.rs
- fake/src/impls/sea_orm/mod.rs
Wanted to use the Dummy derive on a sea-orm model, they have their own UUID. Feedback welcome.
> Add sea orm uuid support

- fake/Cargo.toml
- fake/src/impls/mod.rs
- fake/src/impls/zerocopy_byteorder/mod.rs
I found myself creating wrapper types for the various zerocopy::byteorder structs in order to implement the Dummy trait.
I'm not sure if the fake-rs crates wants to contain a local impl for them, but I added one in this PR.  Feel free to use if desired.
If there is a better way to perform this trait implementation, please let me know.
> Add byteorder dummy

- fake/src/faker/impls/internet.rs
I want to create fake SafeEmail for different locales: ZH_CN, FR_FR (or new additions) for example: 
```
let val: String = SafeEmail(ZH_CN).fake();
println!("{:?}", val);
```
This prints us english names, so it is not the desired result.
SafeEmail names appear only in English locale, or the default Data trait implementation. So it would be nice to add support for different locales.
> Remove hardcoded EN default locale for SafeEmail

- README.md
- fake/Cargo.toml
- fake/README.md
- fake/src/impls/chrono_tz/mod.rs
- fake/src/impls/mod.rs
Add a new feature `chrono-tz` and impl `Dummy` for `chrono_tz::Tz`.
A random timezone is selected from the list of all timezones provided by chrono_tz.
I wasn't sure about the determinism tests, so I skipped them.
> Add chrono_tz support

- dummy_derive/src/lib.rs
- fake/src/faker/impls/administrative.rs
- fake/src/faker/impls/automotive.rs
- fake/src/faker/impls/filesystem.rs
- fake/src/impls/color/mod.rs
- fake/src/impls/decimal/mod.rs
- fake/src/impls/semver/mod.rs
- fake/src/impls/zerocopy_byteorder/mod.rs
- fake/tests/derive_macros.rs
I am using this crate in code generated by `tonic_build` but run into an issue with `fake::Fake` not being in scope for the call to `fake_with_rng`. I am not able to add this import since the code is all generated. 
However, using fully qualified syntax allows the Fake trait to be pulled in scope without explicitly importing it:
```
quote! {
<#faker as #fake>::fake_with_rng::<#field_ty, _>(&#faker, rng)
}
```
This PR includes clippy fixes in the proc macro code and I also ran cargo fmt on the crate. The only functional change is in commit [`0088b8b`](https://github.com/cksac/fake-rs/pull/107/commits/0088b8bebdac98568050c1ac0b8b92bd30b6af6f).
p.s. sorry I messed up the original PR when transferring ownership of my fork so opened this one with the relevant changes
> feat: use fully qualified syntax when calling `fake_with_rng` in derive macro

- fake/Cargo.toml
- fake/src/faker/impls/internet.rs
mails in non english format (like french) used accent username to form mail but this is not correct : mail providers works in ascii.
> accents (ie : éàça) isn't support on mail providers

- fake/examples/fakers.rs
- fake/examples/primitives.rs
- fake/examples/usage.rs
- fake/src/faker/impls/barcode.rs
- fake/src/faker/impls/internet.rs
- fake/src/locales/fr_fr.rs
- Fixes clippy lint https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_cast -  Added in: pre 1.29.0
- Removes unused imports
- Used current stable fmt
I ignored newish lints
- https://rust-lang.github.io/rust-clippy/master/index.html#explicit_auto_deref -  Added in: 1.64.0 
- https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args - Added in 1.66.0
Happy to add those, or create a `clippy.toml` to block those until they are deemed ready to be used here.
> style: clippy fixes and reformat

- fake/Cargo.toml
- fake/src/impls/chrono/mod.rs
- fake/src/impls/chrono_tz/mod.rs
This means that any additional timezones will be supported automatically just as long as `Dummy<Faker>` is implemented for them.
This also updates the `chrono-tz` dependency to the newest major version.
> Allow generating any random DateTime<Tz> where Tz: Timezone + Dummy

- fake/Cargo.toml
- fake/README.md
- fake/src/impls/geo/mod.rs
- fake/src/impls/mod.rs
- fake/src/lib.rs
- fake/tests/determinism.rs
There are many types in the broader GeoRust package collection which may also be added, but not everyone needs those hence the distinction between features `geo_types` and `geo`.
> feat: Add geo support

- fake/src/impls/chrono/mod.rs
- fake/src/impls/sea_orm/mod.rs
Currently there are six warnings like the following emitted during compilation of the chrono features
```rust
warning: use of deprecated struct `chrono::Date`: Use `NaiveDate` or `DateTime<Tz>` instead
--> fake/src/impls/chrono/mod.rs:2:14
|
2 | use chrono::{Date, DateTime, Duration, NaiveDate, NaiveDateTime, NaiveTime, TimeZone, Utc};
|              ^^^^
|
= note: `#[warn(deprecated)]` on by default
```
and one about about the seo_orm feature
```rust
warning: unused import: `Fake`
--> fake/src/impls/sea_orm/mod.rs:1:20
|
1 | use crate::{Dummy, Fake, Faker};
|                    ^^^^
|
= note: `#[warn(unused_imports)]` on by default
```
> Prevent warning about deprecated chrono support

- dummy_derive/src/lib.rs
Without these changes, using dummy_derive in a module that has a child module with the name `fake` or `rand` resulted in confusing compiler error messages.
By using the [extern prelude](https://doc.rust-lang.org/stable/reference/names/preludes.html#extern-prelude) we avoid this issue.
> (dummy_derive) Use external prelude `::fake` to prevent conflicts with local modules

- README.md
- fake/Cargo.toml
- fake/README.md
- fake/src/impls/glam/mod.rs
- fake/src/impls/mod.rs
I like both [glam-rs](https://github.com/bitshifter/glam-rs) and fake-rs, but up until now they wouldn't work together.
For my own purposes I've added glam support for `Vec2`, `Vec3`, `Vec4` and `Mat4`. If there is interest I'd be happy to add some more types (which would be straightforward).
All values are currently completely random, which may not always be the best.
> Add partial support for glam

- fake/src/impls/std/mod.rs
- fake/src/impls/std/num.rs
Another change based on my project needs, this adds dummy implementations for the non-zero numeric types in std. I looked to `impl/std/primitives.rs` for some inspiration on how to implement this.
> Add Dummy implementations for nonzero numeric types

- fake/Cargo.toml
- fake/src/impls/http/mod.rs
So a very simple Uri faking that I mocked up just for some initial comments. One personal thought is I should likely randomly generate how many path segments because `/` may not occur randomly enough - but it may be fine. Also no support of `#` for generating random content bookmarks etc. Generally, kept this simple enough for my usecase without going too much into the minutiae of URIs
> Work on HTTP URI support

- dummy_derive/src/lib.rs
- fake/src/lib.rs
This change exposes the `rand::Rng` as a hidden re-export, allowing users to derive with `Dummy`
without having to add the `rand` crate to their dependencies.
Currently, simple uses like deriving the `Dummy` macro requires one to add the `rand` crate to their
dependency tree, for it to not even be used directly in the code.
> feat: expose rng trait hidden

- Cargo.lock
- README.md
- fake/Cargo.toml
- fake/README.md
- fake/src/impls/bigdecimal/mod.rs
- fake/src/impls/chrono/mod.rs
- fake/src/impls/decimal/mod.rs
- fake/src/impls/std/array.rs
- fake/src/impls/time/mod.rs
This commit does a couple of things, mainly:
* Adds a `{chrono|time}::Precision<N>` struct to control the nanoseconds precision level.
* Enables `bigdecimal-rs` to be used standalone, without requiring `rust_decimal`.
It also uses const generics to implement any array length dummy.
The version was bumped to 2.9.0.
> feat: add precision to time and chrono

- Cargo.lock
- fake/Cargo.toml
- fake/src/faker/impls/internet.rs
- fake/src/lib.rs
- fake/tests/always-true.rs
`deunicode` works with `format!` without allocating a temporary string, and is 160KB smaller than the unmaintained `unidecode`.
> Replace unmaintained dependency

- README.md
- fake/Cargo.toml
- fake/examples/fakers.rs
- fake/src/faker/impls/finance.rs
- fake/src/faker/impls/internet.rs
- fake/src/faker/mod.rs
- fake/tests/determinism.rs
This PR contributes the proposed ISIN faker from issue #151:
- It adds a new faker `Isin`, that generates valid ISINs.
- Updates tests, documentation and examples to include the new faker.
- Bumps the version to 2.10.0
> Add ISIN Faker for finance module

- fake/examples/fakers.rs
- fake/src/impls/http/mod.rs
This adds `Dummy` trait implementations for `Method`, `HeaderName`, `HeaderValue`, `HeaderMap`, `uri::Authority`, `uri::PathAndQuery`, `uri::Scheme`, `Request`, and `Response`.
> Add Dummy trait impls for more http types

- dummy_derive/src/lib.rs
Currently this fails to compile with a cryptic error message:
```rust
#[derive(Dummy)]
struct MyStruct<T> {
field: Vec<T>,
}
```
```
missing generics for struct `MyStruct`
expected 1 generic argument
```
This adds support for deriving `Dummy` trait on types with generics, provided the concrete type will implement `Dummy` as well. Otherwise the error message is more friendly. eg for a type `NoDummyImpl`:
```rust
let g: MyStruct<NoDummyImpl> = Faker.fake();
```
```
the trait bound `NoDummyImpl: fake::Dummy<fake::Faker>` is not satisfied
```
> Allow deriving Dummy with generic types

- fake/src/faker/impls/chrono.rs
- fake/src/impls/chrono/mod.rs
Adds a faker implementation for chrono's `FixedOffset`.
> Add support for chrono FixedOffset

- README.md
- fake/Cargo.toml
- fake/README.md
- fake/src/impls/time/mod.rs
- fake/src/lib.rs
Re-exports time and chrono correctly. Also bumps to 2.9.2.
> fix: re-export correct features

- README.md
- fake/Cargo.toml
- fake/src/impls/mod.rs
- fake/src/impls/ulid/mod.rs
- fake/src/lib.rs
- fake/tests/determinism.rs
Ulid : https://github.com/ulid/spec
> Add ulid support

- fake/Cargo.toml
Glam just release 0.27.0, so let's stay up to date.
I guess I'm just a bit unlucky with timing, usually a couple releases per year, but `0.26.0` was released on the day of my last PR and this one a week later :man_shrugging: 
https://github.com/bitshifter/glam-rs/tags
> Update glam to 0.27.0

- fake/Cargo.toml
- fake/src/impls/bson_oid/mod.rs
- fake/src/impls/mod.rs
- fake/src/lib.rs
- fake/tests/determinism.rs
Hey there,
New to open source PR's so please forgive any mistakes on my end.
On a project I'm currently working with we've been using FakeRS for testing. Our structs require ObjectId fields to operate due to MongoDB. 
ObjectId's aren't deterministic due to their nature, so I'm not quite sure how to write a test for this.
I figured the best option would be to post what's currently working for me on a local branch I've been using and see if you folks are at all interested in this functionality being added or not before going any further.
> feat: Add functionality for bson::oid::ObjectId

- fake/Cargo.toml
This removes four dependencies
https://github.com/proptest-rs/proptest/blob/63ef67c/proptest/Cargo.toml#L22
- rusty-fork
- tempfile
- bit-set
- bit-vec
> Disable unnecessary proptest default features

- fake/Cargo.toml
`glam` has released a new version lately which doesn't generate proper fake data for the `Vec*` structs. This solves the issue.
> Update glam to 0.28

- README.md
- fake/Cargo.toml
- fake/README.md
- fake/src/impls/mod.rs
- fake/src/impls/url/mod.rs
for issue: https://github.com/cksac/fake-rs/issues/189
I think it's best to use https://example.com/ as a fixed URL.
> feat: add url feature

- fake/src/impls/chrono/mod.rs
The year 0000 does not exist by definition, which occasionally causes errors in programs.
The year "0000" is generally considered invalid.
1.  Gregorian and Julian Calendars : These calendars start from year 1. There is no year 0; thus, "0000" is invalid.
2.  ISO 8601 : This international standard allows "0000" to represent the year before 1 AD (i.e., 1 BC). However, this usage is specialized and not common in everyday contexts.
3.  Programming and Databases : Some systems and databases may permit "0000", but this is due to specific technical requirements and is not standard practice.
4.  Historical and Archaeological Contexts : In these fields, the convention is that there is no year 0. The year before 1 AD is 1 BC.
Overall, in most standard and everyday contexts, "0000" is not a valid …
> fix: chrono Date range `0..` to `1..`

- README.md
- fake/Cargo.toml
- fake/src/impls/indexmap/mod.rs
- fake/src/impls/mod.rs
Thanks for this nice library!
This was almost a copy-paste from the `HashMap` one
> feat: support for indexmap

- dummy_derive/src/lib.rs
Hiya, thanks for making `fake`! It's helped me out when testing things, and has even caught a few bugs!
This is a small change to enable using `fake` when re-exporting it from a crate (as one might do with macros, for instance).
Currently, the anchored `::fake` paths effectively require the depending crate to directly depend on `fake`. This removes those, and (as far as I'm aware) should not break anything **except** the probably-rare case where there is another module named `fake` in the current scope, in which case the fix would be to anchor the reference **there**, rather than requiring it universally to avoid that one weird scenario.
Tests still pass, and I've haven't touched the versioning, since I'm not quite sure what the appropriate bump would be for this. If there's any changes …
> adds support for re-exporting crate

- fake/README.md
Seems like a decision was made to go for a major bump instead and this location was missed.
> Fix version in crate readme

- fake/src/impls/chrono/mod.rs
- fake/tests/determinism.rs
This builds up on #146 by adding `Precision::<N>` support for `chrono::NaiveDateTime` and adding some tests for it.
> feat: add Precision::<N> support for chrono::NaiveDateTime

- fake/Cargo.toml
- fake/src/impls/bson_oid/mod.rs
- fake/src/impls/ulid/mod.rs
- fake/src/impls/uuid/mod.rs
- fake/src/lib.rs
This pull request includes several updates, improving documentation, adding new features, and enhancing UUID generation. The most significant changes involve updating documentation for various modules, supporting new UUID versions, and enhancing feature flag descriptions.
* Enhanced feature flag descriptions in `fake/src/lib.rs` to include new integrations and provide clearer explanations.
* Added support for UUID versions 6, 7, and 8 in `fake/src/impls/uuid/mod.rs`, including new structs and `Dummy` trait implementations for each version. [[1]](diffhunk://#diff-150f6104e6eedec4679d4e48467871b00a7a620e43f3c681d53a8c77a3c0a4f2R39-R50) [[2]](diffhunk://#diff-150f6104e6eedec4679d4e48467871b00a7a620e43f3c681d53a8c77a3c0a4f2R107-R153)
* Enabled `doc_cfg` feature for `docs.rs` to improve …
> feat: implement UUID v6, v7 and v8 fake value generation

- fake/Cargo.toml
- fake/src/impls/base64/mod.rs
- fake/src/impls/mod.rs
- fake/src/lib.rs
- fake/tests/determinism.rs
> Implement base64 fakes

- fake/src/impls/std/mod.rs
- fake/src/impls/std/time.rs
This PR implements `Dummy` for `std::time::Duration`.
> feat: implement Dummy for `std::time::Duration`

- fake/Cargo.toml
- fake/src/impls/email_address/mod.rs
- fake/src/impls/mod.rs
This PR implements `Dummy<FreeEmail<L>>` and `Dummy<SafeEmail<L>>` for the `EmailAddress` newtype from the [`email_address`](https://github.com/johnstonskj/rust-email_address) crate.
> feat: implement `Dummy` for `EmailAddress` newtype

- fake/src/lib.rs
By using the Fake re-export of Rng, we are sure that we're picking the right version of Rng, avoiding issues like https://github.com/cksac/fake-rs/issues/229.
> use fake Rnd re-export

- README.md
Today I needed to generate number strings with fake-rs. I quickly found `NumberWithFormat`, but I had no clarity on how to use it and had to read the source code to figure out.
Does the explanation in the change reflect the behaviour correctly? Is this the correct way to document it? (I see no other examples in the README).
> Explain the format string in NumberWithFormat

- fake/examples/fakers.rs
- fake/src/bin/cli/fake_gen.rs
- fake/src/faker/impls/markdown.rs
- fake/src/faker/impls/mod.rs
- fake/src/faker/mod.rs
Output of the example run:
```
"*non*"
"**eos**"
["- illum", "- et", "- et", "- veritatis"]
["1. nobis", "2. delectus", "3. doloribus", "4. suscipit", "5. dolores"]
"[et](https://ipsam)"
"> aut et pariatur adipisci quis in."
["> maxime nisi et sint iure quaerat aut et.", "> velit molestiae sint beatae excepturi adipisci.", "> vel odio eos molestiae."]
"```\nofficia neque ab debitis qui non reprehenderit ut nostrum.\n```"
```
> Adds markdown types to available options
