cksac/fake-rs

README.md, src/faker/internet.rs, src/lib.rs
Very simple implementation for ipv6
=> Added Internet.{ip,ipv4,ipv6}

Cargo.toml, README.md, src/faker/mod.rs, src/faker/time.rs, src/lib.rs, src/locales/en.rs, src/locales/zh_tw.rs
This should implement issue #11 . This is implemented using an optional Cargo feature, so it's disabled by default to minimize unnecessary dependencies and compile time. That can be changed.
@svenstaro ,  can you take a look over this and let me know if this is what you had in mind? The tests in `src/lib.rs` are instructive, and the implementation is all in `src/faker/time.rs`
=> Implement (optional) datetime feature using chrono

Cargo.toml, README.md, src/faker/http.rs, src/faker/mod.rs, src/lib.rs, src/locales/en.rs, src/locales/zh_tw.rs
implement Http faker, currently has only status code
=> implement http faker

README.md
Just fix a little mistake in main README.md
=> Fix format mistake in README.md

README.md, fake/examples/fakers.rs, fake/src/faker/impls/internet.rs, fake/src/faker/mod.rs
Add MAC faker in the internet section
=> Add MAC address faker

README.md, fake/examples/fakers.rs, fake/src/faker/impls/barecode.rs, fake/src/faker/impls/mod.rs, fake/src/faker/mod.rs, fake/src/locales/mod.rs
Inspiration : https://faker.readthedocs.io/en/master/providers/faker.providers.isbn.html?highlight=isbn#faker.providers.isbn
=> implement isbn 10 and 13

README.md, fake/src/impls/uuid/mod.rs, fake/src/lib.rs
=> add uuid related docs

fake/Cargo.toml, fake/src/impls/semver/mod.rs
This fixes #69 by updating our semver use.
=> fix semver support

dummy_derive/Cargo.toml
It would be nice to get this dependency updated in a release to help reduce macro-related compile times (due to duplicate crates) in downstream projects.
=> Update darling dependency to most recent version.

README.md, fake/Cargo.toml, fake/examples/derive.rs, fake/examples/fakers.rs, fake/src/impls/decimal/mod.rs, fake/src/impls/mod.rs, fake/src/lib.rs
Thank you for providing this excellent tool!
This PR introduces [Decimal](https://docs.rs/rust_decimal/latest/rust_decimal/) faking.
I chose not to localize it and go with an enum for configuation. I will most likely supply more configuration options in the future :)
=> Add rust_decimal faking capabilities

README.md
forget on https://github.com/cksac/fake-rs/pull/60
=> complete (forget) README on usage of colors

dummy_derive/Cargo.toml
- The only main difference seems to be that you can remove some darling(default) macro lines for Option<>
=> update darling version restriction

fake/Cargo.toml, fake/src/impls/uuid/mod.rs
relate issue [103](https://github.com/cksac/fake-rs/issues/103)
=> fix uuid timestamp compile error

fake/Cargo.toml, fake/src/impls/std/collections/binary_heap.rs, fake/src/impls/std/collections/btree_map.rs, fake/src/impls/std/collections/btree_set.rs, fake/src/impls/std/collections/hash_map.rs, fake/src/impls/std/collections/hash_set.rs, fake/src/impls/std/collections/linked_list.rs, fake/src/impls/std/collections/mod.rs, fake/src/impls/std/collections/vec.rs, fake/src/impls/std/collections/vec_deque.rs, fake/tests/always-true.rs
Closes https://github.com/cksac/fake-rs/issues/128
=> Allow collections to be never empty

fake/src/faker/impls/finance.rs
Fix for clippy error on master branch
=> Fix clippy error

fake/Cargo.toml, fake/examples/utils.rs
Update glam dependency to latest version.
=> Update glam to 0.26

fake/src/impls/indexmap/mod.rs
Seems like I forgot to add support for `IndexSet`, sorry!
=> feat: support for IndexSet

README.md, dummy_derive/Cargo.toml, fake/Cargo.toml
Possible to cut a minor release for the crate_name feature?
=> Cut a minor release

CHANGELOG.md, fake/Cargo.toml, fake/src/locales/de_de.rs, fake/src/locales/it_it.rs, fake/src/locales/pt_pt.rs
- fix street template string for de_de, it_it and pt_pt locales
- adds company constants for pt_pt locale
=> fix: street template string for de_de, it_it and pt_pt locales

CHANGELOG.md, fake/Cargo.toml
@cksac could we create a release with the bugfixes please?
=> version: 4.3.0

README.md
Forgot to get this in the original PR
=> Update the README.md for markdown

fake/src/locales/fr_fr.rs
- Added the correct postcode / zip code format
- Added the metropolitan France timezone
=> feat(fr_fr): Add address postcode and timezone
